# Site settings
title: "Lightfoot Cloud"
email: "support@lightfoot.cloud"
description: "Lightfoot Cloud" # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lightfoot.cloud" # the base hostname & protocol for your site

twitter_username: "dadhatdaniel"
github_username: "dadhatdaniel"

# Build settings
markdown: kramdown


